import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://cash.rbc.ru/converter.html")
    page.get_by_text("RUR").nth(2).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("GBP").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Фунт стерлингов").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Японская иена").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("USD").first.click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("USD").nth(2).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("GBP").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Японская иена").click()
    page.get_by_text("EUR").first.click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("GBP").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("У меня есть").click()
    page.get_by_text("GBP").first.click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Фунт стерлингов").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Австралийский доллар").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Армянский драм").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Болгарский лев").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Вон Республики Корея").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Датская крона DKK").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Индийская рупия").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Молдавский лей MDL").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Норвежская крона").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Сингапурский доллар").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    page.get_by_text("↓").first.click()
    page.get_by_text("Японская иена").click()
    page.get_by_text("RUR").nth(1).click()
    page.get_by_text("USD").nth(1).click()
    page.get_by_text("EUR").nth(1).click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Австралийский доллар AUD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Азербайджанский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Армянский драм AMD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Белорусский рубль").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Болгарский лев BGN").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Бразильский реал").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Венгерский форинт").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Вон Республики Корея KRW").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Датская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Индийская рупия INR").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Казахстанский тенге").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Канадский доллар").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Киргизский сом").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Китайский юань").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Молдавский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый румынский лей").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Новый туркменский манат").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Норвежская крона NOK").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Польский злотый").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Сингапурский доллар SGD").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Таджикский сомони").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Турецкая лира").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Узбекский сум").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Украинская гривна").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Чешская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Шведская крона").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Швейцарский франк").click()
    page.get_by_text("↓").nth(1).click()
    page.get_by_text("Южноафриканский рэнд").click()
    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
